### ISSUE TITLE
I tried to replicate, but it is not displaying the site on github

### ISSUE THREAD

**Issue by palmierieugenio** [aurora-mareviv/aurora-mareviv.github.io#1]
I've tried this method, but it's not working for me, I don't understand what was my mistake.

https://github.com/palmierieugenio/eugeniopalmieri.github.io

I think I've done something wrong in the connection with Github, do you have any suggestions? What do you think was my mistake?

I think the site works, because I was able to display it correctly on Rstudio (that's why I think the problem is with the connection with Github).

I've tried to use the "hugo-academic" theme and I haven't changed the pictures or the css and js files on the .toml file, but for the rest I think I followed the instrucions and the toml files seem similar.

**Comment by aurora-mareviv** [comment]
Hello,   

Your current folder is named `eugeniopalmieri.github.io`   
I'd suggest you start another project in GitHub named like `[USERNAME].github.io` (`palmierieugenio.github.io`) and follow the same steps. My knowledge of Hugo is still very limited so I only could get it to work well when naming it like this (I'm exploring it though).  

Then your blog should appear when clicking [https://palmierieugenio.github.io/](https://palmierieugenio.github.io/)

If you want to try with a different named repo, you should go to your repo URL > Settings > GitHub Pages section to activate GitHub pages for it (For this, see other tutorials linked in my entry for example).

hope this helps

**Comment by palmierieugenio** [comment]
Thanks, it works now, with the "gcushen/hugo-academic" theme too:

https://palmierieugenio.github.io/
https://github.com/palmierieugenio/palmierieugenio.github.io

:)

**Comment by aurora-mareviv** [comment]
I see, that theme looks awesome! The whole universe of Rmarkdown and blogdown looks amazing to me.
